/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex("book").del();
    await knex("book").insert([
        {
            imageurl: "ms-appx:///Assets/image4.jpg",
            title: "1984",
            publisher: "George Orwell",
            author: "George Orwell",
            isbn: "9780451534852",
            year: 1949,
            selling_price: 10.99,
            purchase_price: 9,
            genre: "Dystopian",
            quantity: 12,
            index: 4,
        },
        {
            imageurl: "ms-appx:///Assets/image9.jpg",
            title: "Animal Farm",
            publisher: "George Orwell",
            author: "George Orwell",
            isbn: "9780451536050",
            year: 1945,
            selling_price: 9.99,
            purchase_price: 9,
            genre: "Allegory",
            quantity: 11,
            index: 9,
        },
        {
            imageurl: "ms-appx:///Assets/image1.jpg",
            title: "The Lord",
            publisher: "J.R.R. Tolkien",
            author: "J.R.R. Tolkien",
            isbn: "9780007567499",
            year: 1954,
            selling_price: 29.99,
            purchase_price: 28,
            genre: "Fantasy",
            quantity: 10,
            index: 1,
        },
        {
            imageurl: "ms-appx:///Assets/image2.jpg",
            title: "Pride",
            publisher: "Jane Austen",
            author: "Jane Austen",
            isbn: "9780140283204",
            year: 1813,
            selling_price: 15.99,
            purchase_price: 14,
            genre: "Classic",
            quantity: 5,
            index: 2,
        },
        {
            imageurl: "ms-appx:///Assets/image3.jpg",
            title: "Killer",
            publisher: "Harper Lee",
            author: "Harper Lee",
            isbn: "9780060735097",
            year: 1960,
            selling_price: 12.99,
            purchase_price: 11,
            genre: "Fiction",
            quantity: 8,
            index: 3,
        },
        {
            imageurl: "ms-appx:///Assets/image5.jpg",
            title: "The Catcher",
            publisher: "J.D. Salinger",
            author: "J.D. Salinger",
            isbn: "9780316769487",
            year: 1951,
            selling_price: 14.99,
            purchase_price: 13,
            genre: "Coming-of-age",
            quantity: 7,
            index: 5,
        },
        {
            imageurl: "ms-appx:///Assets/image6.jpg",
            title: "Harry Potter",
            publisher: "J.K. Rowling",
            author: "J.K. Rowling",
            isbn: "9780590353258",
            year: 1997,
            selling_price: 19.99,
            purchase_price: 18,
            genre: "Fantasy",
            quantity: 15,
            index: 6,
        },
        {
            imageurl: "ms-appx:///Assets/image7.jpg",
            title: "Hitchhiker's",
            publisher: "Douglas Adams",
            author: "Douglas Adams",
            isbn: "9780345390827",
            year: 1979,
            selling_price: 13.99,
            purchase_price: 12,
            genre: "Science Fiction",
            quantity: 9,
            index: 7,
        },
        {
            imageurl: "ms-appx:///Assets/image8.jpg",
            title: "The Great",
            publisher: "F. Scott Fitzgerald",
            author: "F. Scott Fitzgerald",
            isbn: "9780743273563",
            year: 1925,
            selling_price: 16.99,
            purchase_price: 15,
            genre: "Classic",
            quantity: 6,
            index: 8,
        },
        {
            imageurl: "ms-appx:///Assets/image10.jpg",
            title: "Little Prince",
            publisher: "Antoine de Saint-Exupéry",
            author: "Antoine de Saint-Exupéry",
            isbn: "9780446315981",
            year: 1943,
            selling_price: 11.99,
            purchase_price: 10,
            genre: "Children's",
            quantity: 13,
            index: 10,
        },
    ]);
};
